sudo: required
dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install lmodern
install:
 - source ./texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
- mkdir _build
# Prefix command with travis_wait x so it times out after 3 mins
- travis_wait 3 pdflatex -output-directory _build ./main.tex
